---
- name: Verify that required parameters are set
  assert:
    that:
      - '{{ item }} is defined'
      - '{{ item }} | length > 0'
  with_items:
    - docker_url
    - docker_keyring
    - docker_repo
...
